name: Tests for this module

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:

env:
  #Terraform Auth
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    container:
      image: 'aztfmod/rover:2001.2205'
      options: --user 0
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'    
    - name: Terraform Validate
      run: |
        cd examples/pip_single
        terraform init
        terraform validate -no-color
      shell: bash
    - name: Terraform destroy
      run: |
        cd examples/pip_single
        terraform destroy -no-color -auto-approve
      shell: bash
      if: always()
